completed api-registration - Fredrick Rana
fredrickrana/c0622-code-solutions pull request #125
Opened 2022-09-06 22:42 UTC by fredrickrana

![Kapture 2022-09-06 at 15 41 13](https://user-images.githubusercontent.com/103611252/188753100-b40736f9-b617-4932-b880-070678a2ec09.gif)

2022-09-06 22:44 UTC, thebearingedge requested changes

2022-09-06 22:44 UTC, thebearingedge commented on api-registration/server/index.js
> +      returning *;
The client should not receive the hashed password.

2022-09-06 23:01 UTC, fredrickrana commented
![Kapture 2022-09-06 at 15 59 20](https://user-images.githubusercontent.com/103611252/188754872-c4d81d64-0481-485a-9955-98f495b5b867.gif)

2022-09-07 15:32 UTC, thebearingedge approved these changes

2022-09-14 17:47 UTC, merged