completed string-manipulation-1 - Fredrick Rana
fredrickrana/c0622-code-solutions pull request #36
Opened 2022-07-08 23:46 UTC by fredrickrana

![Screen Shot 2022-07-08 at 4 44 20 PM](https://user-images.githubusercontent.com/103611252/178082679-88b1008f-2b43-40d2-94a5-a88e071a5670.png)

2022-07-11 18:09 UTC, codingcodymiller requested changes

2022-07-11 18:09 UTC, codingcodymiller commented on string-manipulation-1/src/capitalize.js
> +  }
You can simplify this considerably by just capitalizing the first letter before the loop, then just use the loop to lowercase each subsequent letter.

2022-07-11 20:29 UTC, fredrickrana commented
![Screen Shot 2022-07-11 at 1 29 02 PM](https://user-images.githubusercontent.com/103611252/178352519-056acf9f-3604-4c58-a06c-47729027d1aa.png)

2022-07-12 19:53 UTC, codingcodymiller approved these changes

2022-07-15 17:36 UTC, merged