completed javascript-carousel - Fredrick Rana
fredrickrana/c0622-code-solutions pull request #63
Opened 2022-07-27 22:42 UTC by fredrickrana

![Kapture 2022-07-27 at 15 39 15](https://user-images.githubusercontent.com/103611252/181384707-0085e55d-21f0-4318-b274-3ffae9ceda2b.gif)
![Kapture 2022-07-27 at 15 41 31](https://user-images.githubusercontent.com/103611252/181384948-d8587af3-3ec0-4ab7-82d0-35a2d9c7d653.gif)

2022-07-27 23:46 UTC, codingcodymiller requested changes

2022-07-27 23:46 UTC, codingcodymiller commented on javascript-carousel/main.js
> +      return;
What if you ever needed to reorganize the order of your images? I wouldn't organize your logic around the images shown being in exactly that order. You should make a variable to keep track of the index of the current image in your array.

2022-07-28 00:16 UTC, fredrickrana commented
Created a variable to keep track of the index of the current image in the array ($currentImage). Variable would allow for reorganization of the order of images without compromising functionality.

2022-07-28 23:29 UTC, codingcodymiller approved these changes

2022-07-29 21:47 UTC, merged